# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rustzz/BSSID_CPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rustzz/BSSID_CPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rustzz/BSSID_CPP/CMakeFiles /home/rustzz/BSSID_CPP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rustzz/BSSID_CPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named shared

# Build rule for target.
shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shared
.PHONY : shared

# fast build rule for target.
shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared.dir/build.make CMakeFiles/shared.dir/build
.PHONY : shared/fast

#=============================================================================
# Target rules for targets named pugixml

# Build rule for target.
pugixml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pugixml
.PHONY : pugixml

# fast build rule for target.
pugixml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/build
.PHONY : pugixml/fast

#=============================================================================
# Target rules for targets named requests

# Build rule for target.
requests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 requests
.PHONY : requests

# fast build rule for target.
requests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requests.dir/build.make CMakeFiles/requests.dir/build
.PHONY : requests/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named history

# Build rule for target.
history: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 history
.PHONY : history

# fast build rule for target.
history/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/history.dir/build.make CMakeFiles/history.dir/build
.PHONY : history/fast

#=============================================================================
# Target rules for targets named bssid

# Build rule for target.
bssid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bssid
.PHONY : bssid

# fast build rule for target.
bssid/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bssid.dir/build.make CMakeFiles/bssid.dir/build
.PHONY : bssid/fast

linux/src/cpp/BSSID.o: linux/src/cpp/BSSID.cpp.o

.PHONY : linux/src/cpp/BSSID.o

# target to build an object file
linux/src/cpp/BSSID.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bssid.dir/build.make CMakeFiles/bssid.dir/linux/src/cpp/BSSID.cpp.o
.PHONY : linux/src/cpp/BSSID.cpp.o

linux/src/cpp/BSSID.i: linux/src/cpp/BSSID.cpp.i

.PHONY : linux/src/cpp/BSSID.i

# target to preprocess a source file
linux/src/cpp/BSSID.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bssid.dir/build.make CMakeFiles/bssid.dir/linux/src/cpp/BSSID.cpp.i
.PHONY : linux/src/cpp/BSSID.cpp.i

linux/src/cpp/BSSID.s: linux/src/cpp/BSSID.cpp.s

.PHONY : linux/src/cpp/BSSID.s

# target to generate assembly for a file
linux/src/cpp/BSSID.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bssid.dir/build.make CMakeFiles/bssid.dir/linux/src/cpp/BSSID.cpp.s
.PHONY : linux/src/cpp/BSSID.cpp.s

linux/src/cpp/History.o: linux/src/cpp/History.cpp.o

.PHONY : linux/src/cpp/History.o

# target to build an object file
linux/src/cpp/History.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/history.dir/build.make CMakeFiles/history.dir/linux/src/cpp/History.cpp.o
.PHONY : linux/src/cpp/History.cpp.o

linux/src/cpp/History.i: linux/src/cpp/History.cpp.i

.PHONY : linux/src/cpp/History.i

# target to preprocess a source file
linux/src/cpp/History.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/history.dir/build.make CMakeFiles/history.dir/linux/src/cpp/History.cpp.i
.PHONY : linux/src/cpp/History.cpp.i

linux/src/cpp/History.s: linux/src/cpp/History.cpp.s

.PHONY : linux/src/cpp/History.s

# target to generate assembly for a file
linux/src/cpp/History.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/history.dir/build.make CMakeFiles/history.dir/linux/src/cpp/History.cpp.s
.PHONY : linux/src/cpp/History.cpp.s

linux/src/cpp/Main.o: linux/src/cpp/Main.cpp.o

.PHONY : linux/src/cpp/Main.o

# target to build an object file
linux/src/cpp/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/linux/src/cpp/Main.cpp.o
.PHONY : linux/src/cpp/Main.cpp.o

linux/src/cpp/Main.i: linux/src/cpp/Main.cpp.i

.PHONY : linux/src/cpp/Main.i

# target to preprocess a source file
linux/src/cpp/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/linux/src/cpp/Main.cpp.i
.PHONY : linux/src/cpp/Main.cpp.i

linux/src/cpp/Main.s: linux/src/cpp/Main.cpp.s

.PHONY : linux/src/cpp/Main.s

# target to generate assembly for a file
linux/src/cpp/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/linux/src/cpp/Main.cpp.s
.PHONY : linux/src/cpp/Main.cpp.s

linux/src/cpp/Parser.o: linux/src/cpp/Parser.cpp.o

.PHONY : linux/src/cpp/Parser.o

# target to build an object file
linux/src/cpp/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/linux/src/cpp/Parser.cpp.o
.PHONY : linux/src/cpp/Parser.cpp.o

linux/src/cpp/Parser.i: linux/src/cpp/Parser.cpp.i

.PHONY : linux/src/cpp/Parser.i

# target to preprocess a source file
linux/src/cpp/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/linux/src/cpp/Parser.cpp.i
.PHONY : linux/src/cpp/Parser.cpp.i

linux/src/cpp/Parser.s: linux/src/cpp/Parser.cpp.s

.PHONY : linux/src/cpp/Parser.s

# target to generate assembly for a file
linux/src/cpp/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/linux/src/cpp/Parser.cpp.s
.PHONY : linux/src/cpp/Parser.cpp.s

linux/src/cpp/Requests.o: linux/src/cpp/Requests.cpp.o

.PHONY : linux/src/cpp/Requests.o

# target to build an object file
linux/src/cpp/Requests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requests.dir/build.make CMakeFiles/requests.dir/linux/src/cpp/Requests.cpp.o
.PHONY : linux/src/cpp/Requests.cpp.o

linux/src/cpp/Requests.i: linux/src/cpp/Requests.cpp.i

.PHONY : linux/src/cpp/Requests.i

# target to preprocess a source file
linux/src/cpp/Requests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requests.dir/build.make CMakeFiles/requests.dir/linux/src/cpp/Requests.cpp.i
.PHONY : linux/src/cpp/Requests.cpp.i

linux/src/cpp/Requests.s: linux/src/cpp/Requests.cpp.s

.PHONY : linux/src/cpp/Requests.s

# target to generate assembly for a file
linux/src/cpp/Requests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requests.dir/build.make CMakeFiles/requests.dir/linux/src/cpp/Requests.cpp.s
.PHONY : linux/src/cpp/Requests.cpp.s

linux/src/cpp/Shared.o: linux/src/cpp/Shared.cpp.o

.PHONY : linux/src/cpp/Shared.o

# target to build an object file
linux/src/cpp/Shared.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared.dir/build.make CMakeFiles/shared.dir/linux/src/cpp/Shared.cpp.o
.PHONY : linux/src/cpp/Shared.cpp.o

linux/src/cpp/Shared.i: linux/src/cpp/Shared.cpp.i

.PHONY : linux/src/cpp/Shared.i

# target to preprocess a source file
linux/src/cpp/Shared.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared.dir/build.make CMakeFiles/shared.dir/linux/src/cpp/Shared.cpp.i
.PHONY : linux/src/cpp/Shared.cpp.i

linux/src/cpp/Shared.s: linux/src/cpp/Shared.cpp.s

.PHONY : linux/src/cpp/Shared.s

# target to generate assembly for a file
linux/src/cpp/Shared.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared.dir/build.make CMakeFiles/shared.dir/linux/src/cpp/Shared.cpp.s
.PHONY : linux/src/cpp/Shared.cpp.s

public/pugixml/pugixml.o: public/pugixml/pugixml.cpp.o

.PHONY : public/pugixml/pugixml.o

# target to build an object file
public/pugixml/pugixml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/public/pugixml/pugixml.cpp.o
.PHONY : public/pugixml/pugixml.cpp.o

public/pugixml/pugixml.i: public/pugixml/pugixml.cpp.i

.PHONY : public/pugixml/pugixml.i

# target to preprocess a source file
public/pugixml/pugixml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/public/pugixml/pugixml.cpp.i
.PHONY : public/pugixml/pugixml.cpp.i

public/pugixml/pugixml.s: public/pugixml/pugixml.cpp.s

.PHONY : public/pugixml/pugixml.s

# target to generate assembly for a file
public/pugixml/pugixml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/public/pugixml/pugixml.cpp.s
.PHONY : public/pugixml/pugixml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bssid"
	@echo "... history"
	@echo "... main"
	@echo "... parser"
	@echo "... pugixml"
	@echo "... requests"
	@echo "... shared"
	@echo "... linux/src/cpp/BSSID.o"
	@echo "... linux/src/cpp/BSSID.i"
	@echo "... linux/src/cpp/BSSID.s"
	@echo "... linux/src/cpp/History.o"
	@echo "... linux/src/cpp/History.i"
	@echo "... linux/src/cpp/History.s"
	@echo "... linux/src/cpp/Main.o"
	@echo "... linux/src/cpp/Main.i"
	@echo "... linux/src/cpp/Main.s"
	@echo "... linux/src/cpp/Parser.o"
	@echo "... linux/src/cpp/Parser.i"
	@echo "... linux/src/cpp/Parser.s"
	@echo "... linux/src/cpp/Requests.o"
	@echo "... linux/src/cpp/Requests.i"
	@echo "... linux/src/cpp/Requests.s"
	@echo "... linux/src/cpp/Shared.o"
	@echo "... linux/src/cpp/Shared.i"
	@echo "... linux/src/cpp/Shared.s"
	@echo "... public/pugixml/pugixml.o"
	@echo "... public/pugixml/pugixml.i"
	@echo "... public/pugixml/pugixml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

